### PR TITLE
Dispatch function

### PR DESCRIPTION
**Pull request by kemalturk**
I added dispatch function for call other managers in a manager. I add this because sometimes we want to refresh other widgets. Name may not be proper. We can change it.

### CODE REVIEW

**Comment by zaiste** [comment]
@kemalturk Thanks for the contribution. Fantastic changes overall! The `dispatch` idea, however, needs polishing, but it's good enough. Let's leave it as-is and we will improve it later.

**Comment by kemalturk** [comment]
You are welcome, @zaiste. I thank you for the helpful videos. You are really good man. 🙏

**Comment by zaiste** [comment]
@kemalturk Thanks for taking time to provide this fantastic changes!

BTW, would it be possible to conform to these [Git guidelines](https://docs.google.com/document/d/1PMog2UTjAogbssxauL2PPVTC1z_qj-WqZt2t2YHAwvM/edit) for the future contributions ? Also, feel free to criticize etc ;)

**Comment by kemalturk** [comment]
@zaiste Ok, i will. I didn't see it sorry.

**Comment by z-tc** [comment]
@kemalturk any example of how dispatch function is imagined to work? also, thanks for great examples @zaiste

**Comment by kemalturk** [comment]
@z-tc You can call dispatch function where ever you want in your Manager class.

For example:

```
class LoginManager extends Manager {

    void logout() {
     dispatch<AuthManager>().setAuthState(AuthState.loggedOut);
   }

 
    @override
   void dispose() {}
 }
```

**Pull request merged**
