### PR TITLE
ErrorHandling

### PR DESCRIPTION
**Pull request by kemalturk**
I added error handling mechanism with example.

### CODE REVIEW

**Comment by kemalturk** [comment]
@zaiste What do you thinking about this? If you didn't like i can change.

**Comment by zaiste** [comment]
@kemalturk it's good. Please give me some time to think about it. I'm currently traveling with a limited computer time. ;) I'll try to answer in few hours or tomorrow if that's OK.

**Comment by kemalturk** [comment]
@zaiste Ok, not problem take your time. Have a nice trip.

**Comment by zaiste** [comment]
@kemalturk I'm apologize for the delay. This slipped through the cracks. I've created a new organization `sprinkle-flutter`. How about we put the examples there?

**Comment by kemalturk** [comment]
@zaiste No problem bro. Im sorry too. I can't look at Github for 1 week. Sorry for late answer. We can do how you want. You are the boss.

**Comment by z-tc** [comment]
I am also interested in contributing, think this is really smooth way to go...

**Comment by kemalturk** [comment]
Ok @z-tc contributions are welcome. First we need to open Discord or Telegram channel for this conversations.

**Comment by zaiste** [comment]
@kemalturk could we update this and add it as a separate example under the [sprinkle-flutter](https://github.com/sprinkle-flutter/) organization ?

**Pull request closed without merging**
